<?php

include_once('Services/Calendar/classes/class.ilDate.php');
include_once('./Services/Calendar/interfaces/interface.ilDatePeriod.php');
include_once('Services/Calendar/classes/class.ilCalendarEntry.php');

/**
 * Model for a calendar entry displayed in ilRoomSharingWeekView.
 *
 * @author Tim Röhrig
 * @version $Id$
 *
 *
 * @ingroup ServicesCalendar
 */
class ilRoomSharingCalendarEntry extends ilCalendarEntry
{
	/**
	 * Constructor
	 *
	 * @access public
	 * @param int cal_entry id
	 *
	 */
	public function __construct($a_id = 0)
	{
		global $ilDB, $ilLog;

		$this->log = $ilLog;
		$this->ilRoomsharingDatabase = new ilRoomsharingDatabase(0);

		if ($this->entry_id = $a_id)
		{
			$this->read();
		}
	}

	/**
	 * clone instance
	 */
	public function __clone()
	{
		$this->entry_id = NULL;
	}

	/**
	 * delete entry is forbidden
	 *
	 * @access public
	 * @static
	 *
	 */
	public static function _delete($a_entry_id)
	{
		return false;
	}

	/**
	 * update is forbidden
	 *
	 * @access public
	 *
	 */
	public function update()
	{
		return false;
	}

	/**
	 * save one entry is forbidden
	 *
	 * @access public
	 *
	 */
	public function save()
	{
		return false;
	}

	/**
	 * delete is forbidden
	 *
	 * @access public
	 * @return
	 */
	public function delete()
	{
		return false;
	}

	/**
	 * read all details for calendarEntry from database
	 *
	 * @access protected
	 * @param
	 *
	 */
	protected function read()
	{
		$info = $this->ilRoomsharingDatabase->getInfoForBooking($this->getEntryId());

		//$this->setLastUpdate(new ilDateTime($row->last_update, IL_CAL_DATETIME, 'UTC'));
		$this->setTitle($info['title']);
		$this->setDescription($info['user'] == '' ? $info['description'] : $info['user'] . '<BR>' . $info['description']);
		$this->setLocation($info['room']);
		//$this->setFurtherInformations($row->informations);
		$this->setFullday(false);
		$this->setAutoGenerated(true);
		//$this->setContextId($row->context_id);
		//$this->setTranslationType($row->translation_type);
		//$this->setCompletion($row->completion);
		$this->setMilestone(false);
		$this->enableNotification(false);

		$this->start = $info['start'];
		$this->end = $info['end'];
	}

	/**
	 * Write users responsible for a milestone is forbidden
	 */
	function writeResponsibleUsers($a_users)
	{

	}

	/**
	 * Read responsible users is forbidden
	 */
	function readResponsibleUsers()
	{

	}

}

?>
