<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:19:11.
 */

class ilRoomSharingDatabasePrivilegesTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabasePrivileges
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabasePrivileges;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getClasses
	 * @todo   Implement testGetClasses().
	 */
	public function testGetClasses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getClassNames
	 * @todo   Implement testGetClassNames().
	 */
	public function testGetClassNames()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getClassById
	 * @todo   Implement testGetClassById().
	 */
	public function testGetClassById()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getPrivilegesOfClass
	 * @todo   Implement testGetPrivilegesOfClass().
	 */
	public function testGetPrivilegesOfClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::setLockedClasses
	 * @todo   Implement testSetLockedClasses().
	 */
	public function testSetLockedClasses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getAssignedClassesForUser
	 * @todo   Implement testGetAssignedClassesForUser().
	 */
	public function testGetAssignedClassesForUser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getLockedClasses
	 * @todo   Implement testGetLockedClasses().
	 */
	public function testGetLockedClasses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getUnlockedClasses
	 * @todo   Implement testGetUnlockedClasses().
	 */
	public function testGetUnlockedClasses()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getPriorityOfClass
	 * @todo   Implement testGetPriorityOfClass().
	 */
	public function testGetPriorityOfClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::setPrivilegesForClass
	 * @todo   Implement testSetPrivilegesForClass().
	 */
	public function testSetPrivilegesForClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::insertClass
	 * @todo   Implement testInsertClass().
	 */
	public function testInsertClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::updateClass
	 * @todo   Implement testUpdateClass().
	 */
	public function testUpdateClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::assignUserToClass
	 * @todo   Implement testAssignUserToClass().
	 */
	public function testAssignUserToClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getUsersForClass
	 * @todo   Implement testGetUsersForClass().
	 */
	public function testGetUsersForClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::deassignUserFromClass
	 * @todo   Implement testDeassignUserFromClass().
	 */
	public function testDeassignUserFromClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::clearUsersInClass
	 * @todo   Implement testClearUsersInClass().
	 */
	public function testClearUsersInClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::deleteClassPrivileges
	 * @todo   Implement testDeleteClassPrivileges().
	 */
	public function testDeleteClassPrivileges()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::deleteClass
	 * @todo   Implement testDeleteClass().
	 */
	public function testDeleteClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::isUserInClass
	 * @todo   Implement testIsUserInClass().
	 */
	public function testIsUserInClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getUserPriority
	 * @todo   Implement testGetUserPriority().
	 */
	public function testGetUserPriority()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabasePrivileges::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
