<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:19:18.
 */

class ilRoomSharingDatabaseRoomAttributeTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseRoomAttribute
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseRoomAttribute;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getAttributesForRooms
	 * @todo   Implement testGetAttributesForRooms().
	 */
	public function testGetAttributesForRooms()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getAllAttributeNames
	 * @todo   Implement testGetAllAttributeNames().
	 */
	public function testGetAllAttributeNames()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getMaxCountForAttribute
	 * @todo   Implement testGetMaxCountForAttribute().
	 */
	public function testGetMaxCountForAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getRoomAttribute
	 * @todo   Implement testGetRoomAttribute().
	 */
	public function testGetRoomAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getAttributesForRoom
	 * @todo   Implement testGetAttributesForRoom().
	 */
	public function testGetAttributesForRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::deleteAllAttributesForRoom
	 * @todo   Implement testDeleteAllAttributesForRoom().
	 */
	public function testDeleteAllAttributesForRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::insertAttributeForRoom
	 * @todo   Implement testInsertAttributeForRoom().
	 */
	public function testInsertAttributeForRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getAllRoomAttributes
	 * @todo   Implement testGetAllRoomAttributes().
	 */
	public function testGetAllRoomAttributes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::deleteRoomAttribute
	 * @todo   Implement testDeleteRoomAttribute().
	 */
	public function testDeleteRoomAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::insertRoomAttribute
	 * @todo   Implement testInsertRoomAttribute().
	 */
	public function testInsertRoomAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::deleteAttributeRoomAssign
	 * @todo   Implement testDeleteAttributeRoomAssign().
	 */
	public function testDeleteAttributeRoomAssign()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::renameRoomAttribute
	 * @todo   Implement testRenameRoomAttribute().
	 */
	public function testRenameRoomAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoomAttribute::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
