<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:21:43.
 */

class ilRoomSharingDatabaseTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabase
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabase;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabase::deletePoolEntry
	 * @todo   Implement testDeletePoolEntry().
	 */
	public function testDeletePoolEntry()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabase::getRoomAgreementId
	 * @todo   Implement testGetRoomAgreementId().
	 */
	public function testGetRoomAgreementId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabase::getUserById
	 * @todo   Implement testGetUserById().
	 */
	public function testGetUserById()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabase::getUserIdByUsername
	 * @todo   Implement testGetUserIdByUsername().
	 */
	public function testGetUserIdByUsername()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabase::getMaxBookTime
	 * @todo   Implement testGetMaxBookTime().
	 */
	public function testGetMaxBookTime()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
