<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:19:07.
 */

class ilRoomSharingDatabaseParticipantsTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseParticipants
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseParticipants;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::insertBookingParticipants
	 * @todo   Implement testInsertBookingParticipants().
	 */
	public function testInsertBookingParticipants()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::insertBookingParticipant
	 * @todo   Implement testInsertBookingParticipant().
	 */
	public function testInsertBookingParticipant()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::updateBookingParticipant
	 * @todo   Implement testUpdateBookingParticipant().
	 */
	public function testUpdateBookingParticipant()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::getParticipantsForBooking
	 * @todo   Implement testGetParticipantsForBooking().
	 */
	public function testGetParticipantsForBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::getParticipantsForBookingShort
	 * @todo   Implement testGetParticipantsForBookingShort().
	 */
	public function testGetParticipantsForBookingShort()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::deleteParticipation
	 * @todo   Implement testDeleteParticipation().
	 */
	public function testDeleteParticipation()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::deleteParticipations
	 * @todo   Implement testDeleteParticipations().
	 */
	public function testDeleteParticipations()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::getParticipationsForUser
	 * @todo   Implement testGetParticipationsForUser().
	 */
	public function testGetParticipationsForUser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::updateBookingParticipants
	 * @todo   Implement testUpdateBookingParticipants().
	 */
	public function testUpdateBookingParticipants()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseParticipants::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
