<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:19:00.
 */

class ilRoomSharingDatabaseCalendarTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseCalendar
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseCalendar;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::getCalendarId
	 * @todo   Implement testGetCalendarId().
	 */
	public function testGetCalendarId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::setCalendarId
	 * @todo   Implement testSetCalendarId().
	 */
	public function testSetCalendarId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::deleteCalendarEntryOfBooking
	 * @todo   Implement testDeleteCalendarEntryOfBooking().
	 */
	public function testDeleteCalendarEntryOfBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::updatingCalendarEntryOfBooking
	 * @todo   Implement testUpdatingCalendarEntryOfBooking().
	 */
	public function testUpdatingCalendarEntryOfBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::deleteCalendar
	 * @todo   Implement testDeleteCalendar().
	 */
	public function testDeleteCalendar()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::deleteCalendarEntriesOfBookings
	 * @todo   Implement testDeleteCalendarEntriesOfBookings().
	 */
	public function testDeleteCalendarEntriesOfBookings()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::updateBookingAppointment
	 * @todo   Implement testUpdateBookingAppointment().
	 */
	public function testUpdateBookingAppointment()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::insertBookingAppointment
	 * @todo   Implement testInsertBookingAppointment().
	 */
	public function testInsertBookingAppointment()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseCalendar::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
