<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:18:50.
 */

class ilRoomSharingDatabaseBookingTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseBooking
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseBooking;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::insertBooking
	 * @todo   Implement testInsertBooking().
	 */
	public function testInsertBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::insertBookingRecurrence
	 * @todo   Implement testInsertBookingRecurrence().
	 */
	public function testInsertBookingRecurrence()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::deleteBooking
	 * @todo   Implement testDeleteBooking().
	 */
	public function testDeleteBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::deleteBookings
	 * @todo   Implement testDeleteBookings().
	 */
	public function testDeleteBookings()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getAllBookingIdsForSequence
	 * @todo   Implement testGetAllBookingIdsForSequence().
	 */
	public function testGetAllBookingIdsForSequence()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getSequenceAndUserForBooking
	 * @todo   Implement testGetSequenceAndUserForBooking().
	 */
	public function testGetSequenceAndUserForBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getBookingsForUser
	 * @todo   Implement testGetBookingsForUser().
	 */
	public function testGetBookingsForUser()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getFilteredBookings
	 * @todo   Implement testGetFilteredBookings().
	 */
	public function testGetFilteredBookings()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getBooking
	 * @todo   Implement testGetBooking().
	 */
	public function testGetBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getAllBookingsForRoom
	 * @todo   Implement testGetAllBookingsForRoom().
	 */
	public function testGetAllBookingsForRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getBookingsForRoomThatAreValid
	 * @todo   Implement testGetBookingsForRoomThatAreValid().
	 */
	public function testGetBookingsForRoomThatAreValid()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getAllBookingsIds
	 * @todo   Implement testGetAllBookingsIds().
	 */
	public function testGetAllBookingsIds()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getBookingIdsForRoomInDateimeRanges
	 * @todo   Implement testGetBookingIdsForRoomInDateimeRanges().
	 */
	public function testGetBookingIdsForRoomInDateimeRanges()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::updateBooking
	 * @todo   Implement testUpdateBooking().
	 */
	public function testUpdateBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getBookingIdForRoomInDateTimeRange
	 * @todo   Implement testGetBookingIdForRoomInDateTimeRange().
	 */
	public function testGetBookingIdForRoomInDateTimeRange()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getInfoForBooking
	 * @todo   Implement testGetInfoForBooking().
	 */
	public function testGetInfoForBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getCurrentBookingsForRoom
	 * @todo   Implement testGetCurrentBookingsForRoom().
	 */
	public function testGetCurrentBookingsForRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::deleteAllBookingsAssignedToRoom
	 * @todo   Implement testDeleteAllBookingsAssignedToRoom().
	 */
	public function testDeleteAllBookingsAssignedToRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getBookingsForRoomInTimeSpan
	 * @todo   Implement testGetBookingsForRoomInTimeSpan().
	 */
	public function testGetBookingsForRoomInTimeSpan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBooking::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
