<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:18:56.
 */

class ilRoomSharingDatabaseBookingAttributeTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseBookingAttribute
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseBookingAttribute;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::insertBookingAttributes
	 * @todo   Implement testInsertBookingAttributes().
	 */
	public function testInsertBookingAttributes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::insertBookingAttributeAssign
	 * @todo   Implement testInsertBookingAttributeAssign().
	 */
	public function testInsertBookingAttributeAssign()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::getAttributesForBooking
	 * @todo   Implement testGetAttributesForBooking().
	 */
	public function testGetAttributesForBooking()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::getAllBookingAttributes
	 * @todo   Implement testGetAllBookingAttributes().
	 */
	public function testGetAllBookingAttributes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::getAllBookingAttributeNames
	 * @todo   Implement testGetAllBookingAttributeNames().
	 */
	public function testGetAllBookingAttributeNames()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::getBookingAttributeValues
	 * @todo   Implement testGetBookingAttributeValues().
	 */
	public function testGetBookingAttributeValues()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::updateBookingAttributeAssign
	 * @todo   Implement testUpdateBookingAttributeAssign().
	 */
	public function testUpdateBookingAttributeAssign()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::updateBookingAttributes
	 * @todo   Implement testUpdateBookingAttributes().
	 */
	public function testUpdateBookingAttributes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::updateDelBookingAttributeAssign
	 * @todo   Implement testUpdateDelBookingAttributeAssign().
	 */
	public function testUpdateDelBookingAttributeAssign()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::deleteAttributeBookingAssign
	 * @todo   Implement testDeleteAttributeBookingAssign().
	 */
	public function testDeleteAttributeBookingAssign()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::deleteBookingAttribute
	 * @todo   Implement testDeleteBookingAttribute().
	 */
	public function testDeleteBookingAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::insertBookingAttribute
	 * @todo   Implement testInsertBookingAttribute().
	 */
	public function testInsertBookingAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::renameBookingAttribute
	 * @todo   Implement testRenameBookingAttribute().
	 */
	public function testRenameBookingAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseBookingAttribute::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
