<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:19:15.
 */

class ilRoomSharingDatabaseRoomTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseRoom
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseRoom;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getMaxSeatCount
	 * @todo   Implement testGetMaxSeatCount().
	 */
	public function testGetMaxSeatCount()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getRoomIdsWithMatchingAttribute
	 * @todo   Implement testGetRoomIdsWithMatchingAttribute().
	 */
	public function testGetRoomIdsWithMatchingAttribute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getAllRoomIds
	 * @todo   Implement testGetAllRoomIds().
	 */
	public function testGetAllRoomIds()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getAllRooms
	 * @todo   Implement testGetAllRooms().
	 */
	public function testGetAllRooms()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getAllRoomNames
	 * @todo   Implement testGetAllRoomNames().
	 */
	public function testGetAllRoomNames()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getMatchingRooms
	 * @todo   Implement testGetMatchingRooms().
	 */
	public function testGetMatchingRooms()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getRoomName
	 * @todo   Implement testGetRoomName().
	 */
	public function testGetRoomName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getRoomWithName
	 * @todo   Implement testGetRoomWithName().
	 */
	public function testGetRoomWithName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getRoomsBookedInDateTimeRange
	 * @todo   Implement testGetRoomsBookedInDateTimeRange().
	 */
	public function testGetRoomsBookedInDateTimeRange()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getAllRoomIdsWhereSeatsAvailable
	 * @todo   Implement testGetAllRoomIdsWhereSeatsAvailable().
	 */
	public function testGetAllRoomIdsWhereSeatsAvailable()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getRoomsWithFloorplan
	 * @todo   Implement testGetRoomsWithFloorplan().
	 */
	public function testGetRoomsWithFloorplan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getRoom
	 * @todo   Implement testGetRoom().
	 */
	public function testGetRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::insertRoom
	 * @todo   Implement testInsertRoom().
	 */
	public function testInsertRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::updateRoomProperties
	 * @todo   Implement testUpdateRoomProperties().
	 */
	public function testUpdateRoomProperties()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::deleteRoom
	 * @todo   Implement testDeleteRoom().
	 */
	public function testDeleteRoom()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseRoom::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
