<?php

chdir("../../../../../../../../"); // necessary for the include paths that are used within the classes to be tested
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 09:19:03.
 */

class ilRoomSharingDatabaseFloorplanTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var ilRoomSharingDatabaseFloorplan
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ilRoomSharingDatabaseFloorplan;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::getAllFloorplans
	 * @todo   Implement testGetAllFloorplans().
	 */
	public function testGetAllFloorplans()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::getFloorplan
	 * @todo   Implement testGetFloorplan().
	 */
	public function testGetFloorplan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::getAllFloorplanIds
	 * @todo   Implement testGetAllFloorplanIds().
	 */
	public function testGetAllFloorplanIds()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::insertFloorplan
	 * @todo   Implement testInsertFloorplan().
	 */
	public function testInsertFloorplan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::deleteFloorplan
	 * @todo   Implement testDeleteFloorplan().
	 */
	public function testDeleteFloorplan()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::deleteFloorplanRoomAssociation
	 * @todo   Implement testDeleteFloorplanRoomAssociation().
	 */
	public function testDeleteFloorplanRoomAssociation()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::setPoolId
	 * @todo   Implement testSetPoolId().
	 */
	public function testSetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ilRoomSharingDatabaseFloorplan::getPoolId
	 * @todo   Implement testGetPoolId().
	 */
	public function testGetPoolId()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
